<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>SD.Slapper.AutoMapper.Strongname</PackageId>
        <Authors>Spectrum Dynamics Medical</Authors>
        <PackageProjectUrl>https://github.com/Spectrum-Dynamics/SD.Slapper.AutoMapper</PackageProjectUrl>
        <PackageLicenseUrl></PackageLicenseUrl>
        <RepositoryUrl>https://github.com/Spectrum-Dynamics/SD.Slapper.AutoMapper</RepositoryUrl>
        <Version>2.1.5</Version>
        <TargetFrameworks>netstandard2.1;net472</TargetFrameworks>
        <Product>Slapper.AutoMapper.Core</Product>
        <Copyright>Copyright (c) 2017-2026, Spectrum Dynamics Medical. All rights reserved.</Copyright>
        <Description>Fork of Slapper.AutoMapper with additional patches. Slapper.AutoMapper is a mapping library that can convert dynamic data into static types and populate complex nested child objects.</Description>
        <PackageTags>Slapper.AutoMapper slapper automapper mapper map dynamic</PackageTags>
        <PackageReleaseNotes>Version 2.1.5</PackageReleaseNotes>
        <PackageLicenseExpression></PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <RepositoryType>git</RepositoryType>
        <PrivateKey />
        <SignAssembly>True</SignAssembly>
        <DelaySign>True</DelaySign>
        <AssemblyOriginatorKeyFile>..\..\SD.Dapper.Public.snk</AssemblyOriginatorKeyFile>
        <IncludeSymbols>true</IncludeSymbols>
       <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>
   
  <PropertyGroup Condition=" '$(PrivateKey)' != '' ">
    <SignAssembly>True</SignAssembly>
    <DelaySign>False</DelaySign>
    <AssemblyOriginatorKeyFile>$(PrivateKey)</AssemblyOriginatorKeyFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

    <ItemGroup>
      <Compile Include="..\Slapper.AutoMapper\CallContext.cs" Link="CallContext.cs" />
      <Compile Include="..\Slapper.AutoMapper\Slapper.AutoMapper.Cache.cs" Link="Slapper.AutoMapper.Cache.cs" />
      <Compile Include="..\Slapper.AutoMapper\Slapper.AutoMapper.Configuration.cs" Link="Slapper.AutoMapper.Configuration.cs" />
      <Compile Include="..\Slapper.AutoMapper\Slapper.AutoMapper.cs" Link="Slapper.AutoMapper.cs" />
      <Compile Include="..\Slapper.AutoMapper\Slapper.AutoMapper.InternalHelpers.cs" Link="Slapper.AutoMapper.InternalHelpers.cs" />
      <Compile Include="..\Slapper.AutoMapper\Slapper.AutoMapper.Logging.cs" Link="Slapper.AutoMapper.Logging.cs" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\LICENSE">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>

</Project>
