<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>SD.Slapper.AutoMapper</PackageId>
        <Authors>Spectrum Dynamics Medical</Authors>
        <PackageProjectUrl>https://github.com/Spectrum-Dynamics/SD.Slapper.AutoMapper</PackageProjectUrl>
        <PackageLicenseUrl></PackageLicenseUrl>
        <RepositoryUrl>https://github.com/Spectrum-Dynamics/SD.Slapper.AutoMapper</RepositoryUrl>
        <Version>2.1.5</Version>
        <TargetFrameworks>netstandard2.1;net472</TargetFrameworks>
        <Product>Slapper.AutoMapper.Core</Product>
        <Copyright>Copyright (c) 2017-2026, Spectrum Dynamics Medical. All rights reserved.</Copyright>
        <Description>Fork of Slapper.AutoMapper with additional patches. Slapper.AutoMapper is a mapping library that can convert dynamic data into static types and populate complex nested child objects.</Description>
        <PackageTags>Slapper.AutoMapper slapper automapper mapper map dynamic</PackageTags>
        <PackageReleaseNotes>Version 2.1.5</PackageReleaseNotes>
        <PackageLicenseExpression></PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <RepositoryType>git</RepositoryType>
        <DefineConstants>$(DefineConstants);NOT_SIGNED</DefineConstants>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>
  
    <ItemGroup>
      <None Include="..\LICENSE">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>

</Project>
